# Site settings
title: M-Lab
email: support@measurementlab.net
baseurl: "/m-lab.github.io"
excerpt_separator: <!--more-->
destination: "_site/m-lab.github.io"

# Build settings
permalink: "/blog/:title/"
sass:
  sass_dir: _sass
markdown: kramdown
include: ['_pages']
exclude:
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock

# Gems
gems: ['jekyll-paginate', 'jekyll-feed']
paginate: 1
paginate_path: "/blog/page/:num"

# HTML Compression settings
compress_html:
  clippings: [ ]
  blanklines: false
  profile: false
